# Generated by Django 3.0.6 on 2023-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_auto_20230617_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(max_length=1000),
        ),
    ]
